/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AInput: typeof import('ant-design-vue/es')['Input']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ChooseWallet: typeof import('./src/components/chooseWallet.vue')['default']
    ErrorInfo: typeof import('./src/components/error-info.vue')['default']
    ErrorMsg: typeof import('./src/components/error-msg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StakeSuccess: typeof import('./src/components/stake-success.vue')['default']
    SuccessMsg: typeof import('./src/components/success-msg.vue')['default']
    Title: typeof import('./src/components/title.vue')['default']
  }
}
